name: React CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Change to your version if needed

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build app
      run: npm run build

    - name: Upload production build
      uses: actions/upload-artifact@v3.1.2
      with:
       name: react-build
       path: build


